const test = require('node:test')
const assert = require('node:assert/strict')
const { setProgressiveList, appendProgressiveList } = require('../services/progressive-list')
const { installWx, instantiatePage } = require('../scripts/benchmark-performance')
const { createFixture } = require('../scripts/performance-fixture')
const flush = () => new Promise(resolve => setImmediate(resolve))
const { setProgressiveModel, cancelProgressiveModel } = require('../services/progressive-list')

test('多段账单分批发送，完整汇总立即保留，最终数据逐字段相同', async () => {
  const { page, payloads } = instantiatePage('pages/statement/statement')
  const model = { shipments: Array.from({ length: 97 }, (_, id) => ({ id: `s${id}` })), payments: Array.from({ length: 62 }, (_, id) => ({ id: `p${id}` })), total: '¥1234.00', received: '¥567.00', outstanding: '¥667.00' }
  setProgressiveModel(page, model, ['shipments', 'payments'])
  assert.equal(page.data.shipments.length, 30)
  assert.equal(page.data.payments.length, 30)
  assert.equal(page.data.total, model.total)
  while (page._progressiveModel) await new Promise(resolve => setTimeout(resolve, 1))
  Object.keys(model).forEach(key => assert.deepEqual(page.data[key], model[key]))
  assert.ok(payloads.slice(1).every(payload => payload.keys.length <= 60 && payload.keys.every(key => /^(shipments|payments)\[\d+\]$/.test(key))))
  setProgressiveModel(page, model, ['shipments', 'payments'])
  assert.equal(page.data.shipments.length, 97)
  assert.ok(!payloads[payloads.length - 1].keys.includes('shipments'), 'unchanged return does not collapse or resend a section')
})

test('账单的新刷新取消旧批次，卸载后不再发送数据，小账单无延时任务', async () => {
  const { page, payloads } = instantiatePage('pages/client-ledger/client-ledger')
  const oldRows = Array.from({ length: 100 }, (_, id) => ({ id: `old${id}` }))
  setProgressiveModel(page, { shipments: oldRows, payments: [] }, ['shipments', 'payments'])
  setProgressiveModel(page, { shipments: [{ id: 'new' }], payments: [] }, ['shipments', 'payments'])
  assert.equal(page._progressiveModel, null)
  await new Promise(resolve => setTimeout(resolve, 5))
  assert.deepEqual(page.data.shipments, [{ id: 'new' }])
  setProgressiveModel(page, { shipments: oldRows, payments: [] }, ['shipments', 'payments'])
  cancelProgressiveModel(page)
  const count = payloads.length
  await new Promise(resolve => setTimeout(resolve, 5))
  assert.equal(payloads.length, count)
})

test('渐进列表小样本不分段，长列表只追加新行并保持完整顺序', () => {
  const { page, payloads } = instantiatePage('pages/clients/clients')
  const items = Array.from({ length: 97 }, (_, id) => ({ id: String(id), name: `第${id}项` }))
  setProgressiveList(page, 'clients', items, { clientCount: items.length })
  assert.equal(page.data.clients.length, 30)
  assert.equal(page.data.clientCount, 97)
  appendProgressiveList(page, 'clients')
  assert.equal(page.data.clients.length, 60)
  assert.ok(payloads[1].keys.every(key => /^clients\[\d+\]$/.test(key)))
  appendProgressiveList(page, 'clients')
  appendProgressiveList(page, 'clients')
  assert.deepEqual(page.data.clients, items)
  const calls = payloads.length
  appendProgressiveList(page, 'clients')
  assert.equal(payloads.length, calls)
  setProgressiveList(page, 'clients', items, {})
  assert.equal(page.data.clients.length, 97, 'return/refresh retains the displayed extent')
  setProgressiveList(page, 'clients', items.slice(0, 4), {}, true)
  assert.deepEqual(page.data.clients, items.slice(0, 4))
  setProgressiveList(page, 'clients', [], {}, true)
  assert.deepEqual(page.data.clients, [])
})

test('客户完整搜索、负责人过滤、总数与排序不受首批30行限制', async () => {
  const fixture = createFixture(97, 97)
  fixture.snapshot.clients[96].ownerMemberId = 'another_member'
  fixture.snapshot.clients[96].phone = 'search-full-list'
  installWx(fixture)
  require('../services/repository-instance').resetRepository()
  const { page } = instantiatePage('pages/clients/clients')
  page.onShow(); await flush()
  assert.equal(page.data.clients.length, 30)
  assert.equal(page.data.clientCount, 97)
  page.onSearch({ detail: { value: 'search-full-list' } })
  assert.deepEqual(page.data.clients.map(row => row.id), ['client_0096'])
  page.setScope({ currentTarget: { dataset: { scope: 'mine' } } })
  assert.equal(page.data.clients.length, 0)
  page.onSearch({ detail: { value: '' } })
  assert.equal(page.data.clientCount, 96)
  while (page.data.clients.length < page.data.clientCount) page.onReachBottom()
  assert.deepEqual(page.data.clients.map(row => row.id), page.allClients.filter(row => row.ownerMemberId === fixture.identity.memberId).map(row => row.id))
  page.onShow(); await flush()
  assert.equal(page.data.clients.length, 96)
})

test('历史的月份和负责人筛选始终作用于全部历史，追加后无丢失或重复', async () => {
  const fixture = createFixture(97, 97)
  const period = fixture.snapshot.billingPeriods.find(row => row.id === 'period_96_settled')
  period.startAt = '2026-06-01T00:00:00.000Z'
  period.closedAt = '2026-06-30T00:00:00.000Z'
  installWx(fixture)
  require('../services/repository-instance').resetRepository()
  const { page } = instantiatePage('pages/history/history')
  page.onShow(); await flush()
  assert.equal(page.data.histories.length, 30)
  const expected = page.allHistories.map(row => row.id)
  while (page.data.histories.length < expected.length) page.onReachBottom()
  assert.deepEqual(page.data.histories.map(row => row.id), expected)
  page.onMonthChange({ detail: { value: String(page.monthValues.indexOf('2026-06')) } })
  assert.deepEqual(page.data.histories.map(row => row.id), ['period_96_settled'])
  page.setScope({ currentTarget: { dataset: { scope: 'mine' } } })
  assert.deepEqual(page.data.histories.map(row => row.id), ['period_96_settled'])
})
